package org.iets3.simulationOutputChecker.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(1);
  /*package*/ final ConceptDescriptor myConceptSimulinkResultDisplayer = createDescriptorForSimulinkResultDisplayer();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptSimulinkResultDisplayer.getId(), 0);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptSimulinkResultDisplayer);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptSimulinkResultDisplayer;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForSimulinkResultDisplayer() {
    return new ConceptDescriptorBuilder("org.iets3.simulationOutputChecker.structure.SimulinkResultDisplayer", MetaIdFactory.conceptId(0x4796fa81351044f2L, 0x9810887e950aacc3L, 0x60b8dfab1590c57L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x22b33c261aecf1d1L, "filePath", new SNodePointer("r:e9507403-d0c6-4ae9-8f38-d17a1f3a0c92(org.iets3.simulationOutputChecker.structure)", "2500408352478917073"))).properties("filePath").childDescriptors(new ConceptDescriptorBuilder.Link(0x60b8dfab159e013L, "simulinkResult", MetaIdFactory.conceptId(0xbe728f68d2954af5L, 0xa9aff280cb60ec85L, 0x57a186429f923e3cL), false, false, false, new SNodePointer("r:e9507403-d0c6-4ae9-8f38-d17a1f3a0c92(org.iets3.simulationOutputChecker.structure)", "435597896828182547")), new ConceptDescriptorBuilder.Link(0x60b8dfab159e014L, "inputCells", MetaIdFactory.conceptId(0xbe728f68d2954af5L, 0xa9aff280cb60ec85L, 0x57a186429f923e40L), true, true, false, new SNodePointer("r:e9507403-d0c6-4ae9-8f38-d17a1f3a0c92(org.iets3.simulationOutputChecker.structure)", "435597896828182548"))).children(new String[]{"simulinkResult", "inputCells"}, new boolean[]{false, true}).rootable().sourceNode(new SNodePointer("r:e9507403-d0c6-4ae9-8f38-d17a1f3a0c92(org.iets3.simulationOutputChecker.structure)", "435597896828128343")).create();
  }
}
